const INPUT_DEBOUNCE_DELAY_MS = 400;
const AVG_WORD_PX_LENGTH = 70;
const WORD_PX_HEIGHT = 50;
const END_INDEX_COEFFICIENT = 2;
const OBSERVER_COEFFICIENT = 0.8;

export {
  INPUT_DEBOUNCE_DELAY_MS,
  AVG_WORD_PX_LENGTH,
  WORD_PX_HEIGHT,
  END_INDEX_COEFFICIENT,
  OBSERVER_COEFFICIENT,
};
